driver/db.go
=> Change the db directory permissions to 777

driver/db.go, driver/virtualdriver.go
=> Remove the mkdir codes

cmd/res/device.virtual.bool.yaml, cmd/res/device.virtual.float.yaml, cmd/res/device.virtual.int.yaml, cmd/res/device.virtual.uint.yaml, driver/virtualdriver.go, go.mod
#6 
Signed-off-by: Trevor Conn <trevor_conn@dell.com>
=> Integrate DeviceProfile Resources / Commands Name Change

cmd/res/configuration.toml, cmd/res/docker/configuration.toml, go.mod
=> Add AutoEvents

cmd/res/device.virtual.bool.yaml, cmd/res/device.virtual.float.yaml, cmd/res/device.virtual.int.yaml, cmd/res/device.virtual.uint.yaml
=> Remove DC "property=value" from device.virtual.*.yaml

Makefile
=> Update project name in makefile

cmd/res/device.virtual.bool.yaml, cmd/res/device.virtual.float.yaml, cmd/res/device.virtual.int.yaml, cmd/res/device.virtual.uint.yaml, driver/db.go, driver/resourcebool.go, driver/resourcefloat.go, driver/resourceint.go, driver/resourceuint.go, driver/virtualdevice.go, driver/virtualdevice_test.go, driver/virtualdriver.go, go.mod
fix #12 #13 
Also update:
1. Recover and update the mkdir codes, PR#5 is my mistaken
2. Move mutex to handleReadCommands and handleWriteCommands to prevent
irregular runtime error when open db
3. Add float encoding Base64 and eNotation to device profile
=> Update to meet CommandValue and CommandRequest refactoring

cmd/res/configuration.toml, cmd/res/docker/configuration.toml
=> Update host name and port number in configuration.toml

go.mod
Upgrade the lib to use the latest device-sdk and core-contract
Fix #22
=> Upgrade to the latest device-sdk and core-contract

Dockerfile, README.md
=> Correct the port number in Dockerfile and README

cmd/res/configuration.toml, cmd/res/docker/configuration.toml, go.mod
=> [edinburgh]Remove ReadMaxLimit and update config 

cmd/res/configuration.toml, cmd/res/docker/configuration.toml, go.mod
=>  Remove ReadMaxLimit and update config

driver/resourcebool.go, driver/resourcefloat.go, driver/resourceint.go, driver/resourceuint.go
=> Readings should be timestamped in nanoseconds

driver/virtualdriver.go
Use sync.Map to replace the basic map type
Fix: #39
=> Fix the thread safe issue in virtualDevices map

Makefile
Signed-off-by: Tyler Powers <tyler.m.powers@intel.com>
=> Add code coverage output file

driver/virtualdriver.go, go.mod
Implement Device CUD callback in protocol driver to fit the change of
device-sdk-go#276
fix: #50 
=> Implement Device CUD callback in protocol driver

cmd/res/docker/configuration.toml
to fit the change of device-virtual-go PR#51
fix: #49 
=> Modify the resource names in docker/configuration.toml

cmd/res/device.virtual.bool.yaml, cmd/res/device.virtual.float.yaml, cmd/res/device.virtual.int.yaml, cmd/res/device.virtual.uint.yaml, driver/virtualdriver.go, go.mod
=> Use new ResourceOperation fields

go.mod
=> Update go.mod with latest device SDK

Attribution.txt, Makefile, bin/test-attribution-txt.sh, bin/test-go-mod-tidy.sh, go.mod
Signed-off-by: Iain Anderson <iain@iotechsys.com>
=> Add Attribution file and extend maketest to check it (#66)

internal/driver/virtualdriver.go
log and return an error instead of panic directly
fix: #76 
=> Handle error in retrieceVirtualDevice func

internal/driver/virtualdriver.go
=> Rename the deprecated field in contracts

Dockerfile
ITM-475 WORKDIR fix
Signed-off-by: Ginny Guan <ginny@iotechsys.com>
=> Update dockerfile to fix build docker image failed

go.mod
=> Upgrade SDK version

go.mod, internal/driver/db.go, internal/driver/resourcefloat.go, internal/driver/resourceint.go, internal/driver/resourceuint.go
=> fix: Resolve potential data race

cmd/res/configuration.toml
=> refactor: remove binary autoevent

go.mod
=> upgrade sdk version to v1.2.1 for Geneva release

.github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: James Gregg <james.r.gregg@intel.com>
Update PR template per decision in Architect's meeting on 06/15/2020 to include section on new added dependencies (e.g. import / modules)
Issue Number:
=> docs: update pr template to include dependencies section

Dockerfile
Signed-off-by: Koppolu <venkata.subbareddy.koppolu@intel.com>
Issue Number:
https://github.com/edgexfoundry/device-virtual-go/issues/125
=> refactor: update dockerfile to appropriately use ENTRYPOINT and CMD, closes#125

Attribution.txt, Dockerfile, Dockerfile.build, Jenkinsfile, bin/test-attribution-txt.sh, go.mod
=> build: upgrade to use Go1.15

go.mod, internal/driver/virtualdriver.go
Issue Number: Fix https://github.com/edgexfoundry/device-virtual-go/issues/130
upgrade device-sdk-go to v1.2.4-dev.13
=> build: upgrade device-sdk-go

cmd/res/device.virtual.bool.yaml, cmd/res/device.virtual.float.yaml, cmd/res/device.virtual.int.yaml, cmd/res/device.virtual.uint.yaml, internal/driver/helper.go, internal/driver/resourcebinary.go, internal/driver/resourcebool.go, internal/driver/resourceboolarray.go, internal/driver/resourcefloat.go, internal/driver/resourcefloatarray.go, internal/driver/resourceint.go, internal/driver/resourceintarray.go, internal/driver/resourceuint.go, internal/driver/resourceuintarray.go, internal/driver/virtualdevice.go, internal/driver/virtualdevice_test.go
device-virtual-go cannot generate random values for array value types.
Issue Number: fix #112 
device-virtual-go can now generate random values ​​for the following array value types:
- BoolArray
- Int8Array, Int16Array, Int32Array, Int64Array
- Uint8Array, Uint16Array, Uint32Array, Uint64Array
- Float32Array, Float64Array
The array size is hardcoded as 5.
Added device resources with these array value types to the sample device profiles, the related device commands and core commands are added as well.
=> feat: Support array value type

go.mod
Signed-off-by: Iain Anderson <iain@iotechsys.com>
Bumps github.com/edgexfoundry/go-mod-core-contracts from 0.1.97 to 0.1.111.
=> build: update go-mod-core-contracts to 0.1.111

go.mod
fix #151 
Bumps github.com/edgexfoundry/device-sdk-go from v1.3.0 to v1.3.1-dev.4
Bumps github.com/edgexfoundry/go-mod-core-contracts from v0.1.111 to v0.1.115
=> build: update device-sdk-go to v1.3.1-dev.4

go.mod
Fix #164
The current sdk version is v1.3.1-dev.11
Issue Number: #164 
Upgrade to v1.4.0
=> refactor: Upgrade SDK to v1.4.0

Attribution.txt, cmd/main.go, cmd/res/configuration.toml, cmd/res/device.virtual.binary.yaml, cmd/res/device.virtual.bool.yaml, cmd/res/device.virtual.float.yaml, cmd/res/device.virtual.int.yaml, cmd/res/device.virtual.uint.yaml, go.mod, internal/driver/helper.go, internal/driver/resourcebinary.go, internal/driver/resourcebool.go, internal/driver/resourceboolarray.go, internal/driver/resourcefloat.go, internal/driver/resourcefloatarray.go, internal/driver/resourceint.go, internal/driver/resourceintarray.go, internal/driver/resourceuint.go, internal/driver/resourceuintarray.go, internal/driver/virtualdevice.go, internal/driver/virtualdevice_test.go, internal/driver/virtualdriver.go
=> refactor: consume v2 Device SDK

go.mod
=> build: bump SDK version

go.mod
=> build: Bump device sdk version

Dockerfile, Dockerfile.build, go.mod
This PR updates the build to use go 1.16.
- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)
=> fix(build): update for go 1.16

Makefile, cmd/res/configuration.toml, go.mod
Latest SDK which removed shared code which forced ZMQ dependency on all services.
Added Missing InscureSecrets
=> refactor: Secure MessageBus Rework

cmd/res/configuration.toml
to be consistent with other device services.
=> fix: update default service configuration

cmd/res/configuration.toml, go.mod, internal/driver/helper.go, internal/driver/resourcebinary.go, internal/driver/resourcebool.go, internal/driver/resourceboolarray.go, internal/driver/resourcefloat.go, internal/driver/resourcefloatarray.go, internal/driver/resourceint.go, internal/driver/resourceintarray.go, internal/driver/resourceuint.go, internal/driver/resourceuintarray.go, internal/driver/virtualdevice.go, internal/driver/virtualdevice_test.go, internal/driver/virtualdriver.go
=> refactor: bump dependency version and update import path

go.mod
- Update sdk to v2.0.0-dev.85
- Update core-contracts to v2.0.0-dev.103
=> build: Update sdk and core-contracts lib

go.mod
SDK with bad go-mod-messaging used
Latest SDK with good go-mod-messaging used
=> build: update to latest SDK

GOVERNANCE.md, OWNERS.md, cmd/res/configuration.toml, cmd/res/devices/devices.toml
also added governance.md and owner.md files for LF Edge
Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>
=> fix: update all TOML to use quote and not single-quote

Attribution.txt, go.mod
Signed-off-by: Cloud Tsai <cloudxxx8@gmail.com>
=> build: Bump device-sdk-go/v2 to 2.0.1-dev.17

Makefile
CGO not needed on Windows w/o ZMQ and causes error if enabled on Windows due to modernc.org dependencies. 
Signed-off-by: lenny <leonard.goodell@intel.com>
**N/A for Build PR**
**N/A for Build PR**
=> build: Make w/o cgo on Windows

bin/test-attribution-txt.sh, go.mod
Changes related to Go 1.17 module changes
=> ci: gomod changes related for Go 1.17

Dockerfile, Makefile, bin/test-attribution-txt.sh, go.mod, go.sum, snap/local/helper-go/Makefile, snap/local/helper-go/go.mod, snap/snapcraft.yaml
also optimized the test-attribution script
Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>
=> build: Upgrade to Go 1.18 and alpine 3.16

snap/README.md, snap/local/helper-go/configure.go, snap/local/helper-go/go.mod, snap/local/helper-go/go.sum, snap/local/helper-go/install.go
- Use library function for autostart processing and config processing
- Replace deprecated hooks package with env package
Signed-off-by: Mengyi Wang <mengyi.wang@canonical.com>
=> build(snap): Upgrade snap hook to 2.4.1

cmd/res/configuration.toml, go.mod, go.sum
=> feat: add internal message request/response topics

cmd/res/configuration.toml
=> fix: add device service key in CommandRequestTopic

snap/local/helper-go/install.go
Signed-off-by: Mengyi Wang <mengyi.wang@canonical.com>
=> refactor(snap): Remove duplicate file copying in install hook

cmd/res/configuration.toml
=> fix: update example request/response topic scheme

internal/driver/virtualdriver.go
=> fix: Update deviceprofile resources for UpdateDevice

Dockerfile, Makefile, go.mod, internal/driver/helper.go, internal/driver/resourcebinary.go, internal/driver/resourcebool.go, internal/driver/resourceboolarray.go, internal/driver/resourcefloat.go, internal/driver/resourcefloatarray.go, internal/driver/resourceint.go, internal/driver/resourceintarray.go, internal/driver/resourceuint.go, internal/driver/resourceuintarray.go, snap/local/helper-go/go.mod, snap/snapcraft.yaml
verify make docker works
Run non-secure EdgeX stack w/o Device Virtual
Build and run service from command line
Verify logs have no errors bootstrapping.
Verify that auotevents are triggering and Events are pushed to the MessageBus
=> build: Update to Go 1.20, Alpine 3.17 and linter v1.51.2

internal/driver/virtualdriver.go
Update Discover func error message to lowercase
=> fix: Update Discover func error message

Attribution.txt, Dockerfile, Makefile, go.mod
make test
make build
make docker
Verify all are successful
=> build: Upgrade to go-1.21, Linter1.54.2 and Alpine 3.18

Makefile, README.md, go.mod, go.sum
related to https://github.com/edgexfoundry/go-mod-bootstrap/pull/795
To allow to build services without openziti, add new targte build-noziti and docker-noziti into Makefile. Also revise README.md to include such information.
=> feat: Add new build-noziti and docker-noziti targets into Makefile
