README.md
cmd/res/device.virtual.bool.yaml
cmd/res/device.virtual.float.yaml
cmd/res/device.virtual.int.yaml
cmd/res/device.virtual.uint.yaml
driver/resourcebool.go
driver/resourcefloat.go
driver/resourceint.go
driver/resourceuint.go
driver/virtualdevice.go
driver/virtualdevice_test.go
driver/virtualdriver.go

Support value type:
Bool,
Int8, Int16, Int32, Int64,
Uint8, Uint16, Uint32, Uint64
Float32, Float64
Restricted: To control the randomization of device resource values, we
have to add additional device resources with the prefix
"**EnableRandomization_**" for each device resource.
(Need to do the same for device commands and core commands)
Please find the default device profile for example
fix: #17 

Decouple the hardcoded device resource names

---

Dockerfile

Add flag "--registry=consul://edgex-core-consul:8500" to the Dockerfile
ENTRYPOINT
fix: #57 

Update docker entrypoint params to run with consul

---

driver/virtualdriver.go

DisconnectDevice func has been removed from protocoldriver interface of Device SDK
fix: #74 

Remove DisconnectDevice function

---

internal/driver/virtualdevice_test.go

Reduce the rounds of generating and checking random value in unit test from 100 to 10 to improve the time consumption.
Resolve: #91 
Issue Number: #91 
N/A

Reduce time consumption of unit test

---

README.md
cmd/res/configuration.toml
cmd/res/device.virtual.binary.yaml
internal/driver/resourcebinary.go
internal/driver/virtualdevice.go
internal/driver/virtualdevice_test.go
internal/driver/virtualdriver.go

fix #115 
Issue Number: [115](https://github.com/edgexfoundry/device-virtual-go/issues/115)
- Won't store binary value in ql DB
- For now, the generation of binary values is always randomized. It's acceptable until device-sdk-go supports binary value for HTTP PUT command

fix: High memory usage

---

cmd/res/device.virtual.bool.yaml
cmd/res/device.virtual.float.yaml
cmd/res/device.virtual.int.yaml
cmd/res/device.virtual.uint.yaml

In the sample device profiles, ReadWrite field of PropertyValue of each device resource should be RW, because they all support the Put command, except for Binary.
fix: #123 
The value of the ReadWrite permission field of PropertyValue of each device resource is `R`.
Issue Number: #123 
All the device resources but Binary can be operated via get/put command, so the ReadWrite permission fields of these device resources are now set to `RW`.

fix: ReadWrite field of each device resource should be RW

---

go.mod

Signed-off-by: Tony Espy <espy@canonical.com>
- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)
This PR updates device-virtual-go to the latest device-sdk-go release 1.3.0.
NA
No
I tested this by building device-virtual-go as part of the main edgexfoundry snap. I installed, enabled device-virtual (to start it), and verified that the version logged was correct (we set VERSION explicitly in the snap build), and that auto event readings were being generated and no other error messages were see in the log output.

build: update device-sdk-go to 1.3.0

---

internal/driver/virtualdriver.go

`prepareVirtualResources` would fail because not able to find profile in cache.
This bug wasn't found out earlier because device-virtual using the same name for example devices and profiles:
https://github.com/edgexfoundry/device-virtual-go/blob/bfe8b6d03e48aca57198d29dac0aa5fe93ed02ec/cmd/res/configuration.toml#L47-L48

fix: pass correct argument in prepareVirtualResources

---

.gitignore
Dockerfile
cmd/res/configuration.toml
go.mod

closes 
Signed-off-by: lenny <leonard.goodell@intel.com>
Registry/Config access tokens capability now  supported
Registry/Config access tokens capability not supported
BREAKING CHANGE: When run with the secure Edgex Stack now need to have the SecretStore configured, a Vault token created and run with EDGEX_SECURITY_SECRET_STORE=true.

feat: Add Registry/Config Access token capability

---

Dockerfile
Makefile
cmd/res/configuration.toml
cmd/res/devices/devices.toml
go.mod

**Dependent on edgexfoundry/go-mod-core-contracts#613
Dependent on edgexfoundry/go-mod-bootstrap#216
Dependent on https://github.com/edgexfoundry/device-sdk-go/pull/926**
Service key constants have the edgex- prefix
Service key constants no longer have the edgex- prefix
Hyphen in Overrides are converted to underscore
BREAKING CHANGE: Service key names used in configuration have changed.

refactor: Update for new service key names and overrides for hyphen to underscore

---

Dockerfile
cmd/res/configuration.toml

Ports assigned for Core/Supporting services are 408xx range
Device Virtual uses  49990 
Ports assigned for Core/Supporting services are 588xx range
Device Virtual now uses 59900 
BREAKING CHANGE: Device Virtual default port number has changed to 59900

refactor: Update to assign and uses new Port Assignments

---

internal/driver/resourceboolarray.go
internal/driver/resourcefloatarray.go
internal/driver/resourceintarray.go
internal/driver/resourceuintarray.go

v2 API `CommandValue.ValueToString()` will return string by just calling `fmt.Sprintf("%v", cv.Value)`.
For array data type the string format would be `[1 2 3 4]`, which is different from v1: `[1, 2, 3, 4]`
So we need to update the split separator.

fix: update separator for GET array value handler function

---

cmd/res/configuration.toml
go.mod

`go-mod-bootstrap` has implemented the addition of prefix `/v1/secret/edgex/` for the Path property of SecretStore config section, so we just use the service specific secret path in Toml files
and also remove the retry related items
Closes: #215
Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>
retry item still exists and should be removed. 
Path element for secret path should change from its full path to just service specific in toml file
Remove retry related in SecretStore section
Update secret path to just contain service …

refactor: Remove retry items of SecretStore config and update secret path

---

internal/driver/virtualdriver.go

- Remove unnecessary update device logic in the UpdateDevice callback function.
- Optimize defer statements.
- Use formatted versions of logging APIs and fine tune err messages.
The virtual device resources are refreshed every time the UpdateDevice callback gets called.
#234 
Remove unnecessary update device logic in the UpdateDevice callback function.
fix: #234

fix: Set command doesn't work as expected when UpdateLastConnected is enabled

---

cmd/res/configuration.toml

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>
For edgex-compose compose-builder make gen ds-virtual delayed-start; docker-compose up -d

feat(security): Roll out delayed start configuration.toml scaffolding

---

.github/workflows/snap.yaml
snap/snapcraft.yaml

remove unused `make tidy`
Signed-off-by: Mengyi Wang <mengyi.wang@canonical.com>

build(snap): Upgrade snap base to core22

---

snap/snapcraft.yaml

As device-virtual snap has not been released yet, this PR is a fix for the development release.
Signed-off-by: Mengyi Wang <mengyi.wang@canonical.com>

fix(snap): Set unique name for config interface

---

Dockerfile
Makefile
README.md
cmd/res/configuration.toml

Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>
Run the following commands and verify each Go build step includes `-tags "include_nats_messaging ...`
```
make build-nats
make docker-nats
```

build: Add option to build Core/Support services with NATS Capability

---

Attribution.txt
cmd/res/configuration.toml

Also updated to latest SDK which brought in more NATS dependencies
Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>
run `make build-nats`
verify see `-tags "include_nats_messaging"  in the Go build line
run `make docker-nats`
verify see `-tags "include_nats_messaging"  in the Go build line
New dependencies are from our own go-mod-messaging module. Not new to EdgeX

feat: Add NATS Subject configuration

---

internal/driver/helper.go
internal/driver/resourcebinary.go
internal/driver/resourcebool.go
internal/driver/resourceboolarray.go
internal/driver/resourceintarray.go

the generator is seeded randomly at program startup now, so remove the Seed function
close #358

feat: Remove deprecated rand.Seed function

---

go.mod
go.sum
internal/driver/virtualdriver.go

BREAKING CHANGE: Consume SDK interface changes by adding Discover and ValidateDevice func on driver
Run core services and device service to verify func works

feat!: Consume SDK interface changes

---

Makefile

1. Run non-secure edgex stack from compose builder
```
make run no-secty 
```
2. build service from this branch `make build`
3. Verify it builds properly
4. ensure security is off `export EDGEX_SECURITY_SECRET_STORE=false`
5. run service
```
./device-virtual -cp -d -o
```

build: [Device Virtual] Add ldflags to strib debug info from binary
